@authors=http://localhost:8080/author

GET {{authors}}/ HTTP/1.1

###
POST {{authors}}/1
Content-Type: application/json

{
    "name":"Xasanboy Abdurasulov"
}

###
PUT {{authors}}/1
Content-Type: application/json

{
    "authorID":1,
    "name":"Xusinboy"
}
###
DELETE {{authors}}/1
Content-Type: application/json

{
    "authorID":3
}